defaultIndent: "    "
verbatimEnvironments:
  lstlisting: 1
  codelisting: 1
  luacode: 1
  luacode*: 1
# Disable \directlua indentations
specialBeginEnd:
  directlua:
    begin: \\directlua
    end: (?:\s*\{[^}]*\})+
    lookForThis: verbatim
